spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    props:
      sql:
        # 显示sql，默认为false
        show: true
    sharding:
      # 配置数据库主从关系，可以多主多从
      masterSlaveRules:
        #随便定义的一个名字
        masterSlave1:
          masterDataSourceName: tb0
          slaveDataSourceNames: tb1
          # 算法，ROUND_ROBIN 轮询， RANDOM 随机
          loadBalanceAlgorithmType: ROUND_ROBIN
    datasource:
      names: tb0,tb1
      tb0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://8.136.207.24:3306/sharding1?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
        username: root
        password: sy1998-+
        minimum-idle: 10
        max-active: 400
        idle-timeout: 600000
        pool-name: tb0HikariCP
        connection-timeout: 30000
      tb1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://8.136.207.24:3306/sharding2?useUnicode=true&characterEncoding=UTF8&serverTimezone=Hongkong
        username: root
        password: sy1998-+
        minimum-idle: 10
        max-active: 400
        idle-timeout: 600000
        pool-name: tb1HikariCP
        connection-timeout: 30000