spring:
  datasource:
    # 默认数据源
    defaultSource: mysql
    dataSource:
      mysql:
         #zookeeper 地址
         url: jdbc:mysql://123.56.97.130:3306/whale?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
         driver-class-name: com.mysql.cj.jdbc.Driver
         # 如果不想配置对数据库连接池做特殊配置的话,以下关于连接池的配置就不是必须的
         type: com.zaxxer.hikari.HikariDataSource
         username: root
         password: sy91aa

         # 池中维护的最小空闲连接数
         minimum-idle: 10
         # 池中最大连接数，包括闲置和使用中的连接
         maximum-pool-size: 20
         idle-timeout: 30000
         pool-name: mysql-hikari
      phoenix:
        #zookeeper 地址
        url: jdbc:phoenix:101.200.155.94:2181
        driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
        type: com.zaxxer.hikari.HikariDataSource
        minimum-idle: 10
        maximum-pool-size: 20
        idle-timeout: 50000
        pool-name: phoenix-hikari

logging:
  level:
    com.sy: debug
    org.springframework: info
    springboot.dao: debug
    org.apache.phoenix: debug
    org.apache.hadoop: debug

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.sy.ex.hbase.domain
  global-config:
    # 不显示banner
    banner: false
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO