spring:
  datasource:
    #zookeeper 地址
    url: jdbc:phoenix:101.200.155.94:2181
    driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    # 如果不想配置对数据库连接池做特殊配置的话,以下关于连接池的配置就不是必须的
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 10
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为。默认为 true
      auto-commit: true
      # 允许最长空闲时间
      idle-timeout: 30000
      # 此属性表示连接池的用户定义名称，主要显示在日志记录和 JMX 管理控制台中，以标识池和池配置。 默认值：自动生成
      pool-name: custom-hikari
      #此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 1800000 即 30 分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认 30 秒，即 30000
      connection-timeout: 30000
      # 连接测试 sql 这个地方需要根据数据库方言差异而配置 例如 oracle 就应该写成  select 1 from dual
      connection-test-query: SELECT 1
logging:
  level:
    com.sy: debug
    org.springframework: info
    springboot.dao: debug
    org.apache.phoenix: debug
    org.apache.hadoop: debug

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.sy.ex.hbase.domain
  configuration:
    call-setters-on-nulls: true